### ISSUE TITLE
How to use the [TablePerType] attribute?

### ISSUE THREAD

**Issue by jnpwly** [Smartrak/SqlMapperExtensions.Smartrak#1]
Hi @danzel. I;m working with @ajbeaven on some bits and bobs, and am looking at the additions you've made to the SqlMapperExtensions. I'm wanting to use the [TablePerType] attribute... but not *entirely* sure how to use it.

You've said, "You'll need to have a type field on the base class which you'll need to use yourself to decide what type each row is." Can you point me as to *how* to go about doing this? Would it be a case of querying for a dynamic object,and then "multi-mapping" that dynamic object (based on the column which determines the concrete class) to the the required output...??

Do you have an example that you could point to? I've been running round in circles for the past couple of days, and I think I'm going a bit loopy!!

Many thanks for your time--I really appreciate it.

**Comment by danzel** [comment]
Hey sorry I have no idea.
I wrote this when I was at Smartrak, I no longer work there, so I don't have access to any code that uses it.
I don't even have access to close this issue or fix any code.

**Comment by jnpwly** [comment]
Ha! That's OK @danzel, people move on, code gets left behind ;) Thanks for your response, I appreciate it. Hope all is good in the Tron.
